# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_service_pb2 as agent__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agent_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentAdapterServiceStub(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    AgentAdapterService is implemented by adapter backends (e.g. LangGraph,
    AgentFramework, Semantic Kernel, etc.) and called by the FoundryCBAgent
    core server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/azure.ai.agentserver.v1.AgentAdapterService/Run',
                request_serializer=agent__service__pb2.AgentRequest.SerializeToString,
                response_deserializer=agent__service__pb2.AgentResponse.FromString,
                _registered_method=True)
        self.RunStream = channel.unary_stream(
                '/azure.ai.agentserver.v1.AgentAdapterService/RunStream',
                request_serializer=agent__service__pb2.AgentRequest.SerializeToString,
                response_deserializer=agent__service__pb2.AgentStreamEvent.FromString,
                _registered_method=True)


class AgentAdapterServiceServicer(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    AgentAdapterService is implemented by adapter backends (e.g. LangGraph,
    AgentFramework, Semantic Kernel, etc.) and called by the FoundryCBAgent
    core server.
    """

    def Run(self, request, context):
        """Non-streaming agent invocation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunStream(self, request, context):
        """Server-streaming agent invocation.  The adapter yields events as
        the agent produces output.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentAdapterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=agent__service__pb2.AgentRequest.FromString,
                    response_serializer=agent__service__pb2.AgentResponse.SerializeToString,
            ),
            'RunStream': grpc.unary_stream_rpc_method_handler(
                    servicer.RunStream,
                    request_deserializer=agent__service__pb2.AgentRequest.FromString,
                    response_serializer=agent__service__pb2.AgentStreamEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'azure.ai.agentserver.v1.AgentAdapterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('azure.ai.agentserver.v1.AgentAdapterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentAdapterService(object):
    """---------------------------------------------------------------------------
    Service definition
    ---------------------------------------------------------------------------

    AgentAdapterService is implemented by adapter backends (e.g. LangGraph,
    AgentFramework, Semantic Kernel, etc.) and called by the FoundryCBAgent
    core server.
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/azure.ai.agentserver.v1.AgentAdapterService/Run',
            agent__service__pb2.AgentRequest.SerializeToString,
            agent__service__pb2.AgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/azure.ai.agentserver.v1.AgentAdapterService/RunStream',
            agent__service__pb2.AgentRequest.SerializeToString,
            agent__service__pb2.AgentStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
